### ISSUE TITLE
Just a thanks

### ISSUE THREAD

**Issue by RemiDesgrange** [JamesHarrison/otdrs#1]
I just want to say thank you for this lib. I'm one the maintainer of https://github.com/sid5432/pyOTDR and there are stuff that I did not understand in the files (I do not have access to the document). Your code is ultra-readable, even if I'm not fluent in Rust.

Shoutout ❤️

**Comment by JamesHarrison** [comment]
Thanks so much for the very kind feedback! Your library inspired me to write this originally - I wanted a Rust implementation after tinkering with yours for a project - and I am really amazed by how correct and complete pyOTDR is as a clean-room reverse-engineering effort! Thank you for your work.
